name: norminette

on:
  pull_request:
    branches: [ "main" ]

jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: config env
        run: |
          sudo apt-get install -y python3
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install norminette
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: test norminette on src
        run: norminette src/

      - name: test norminette on inc
        run: norminette inc/
